name: PRD - ClashOfHeroes Deploy from Staging

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_NAME: clash-of-heroes
      BUILDER_TOKEN: ${{ secrets.BUILDER_TOKEN  }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-northeast-1
      CDN_DISTRIBUTION_ID: ERL61ONO6FPJO
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          path: ClashOfHeroes
      - uses: actions/checkout@v2
        with:
          repository: Elysium-Studios/infrastructure
          token: ${{ env.BUILDER_TOKEN }}
          path: infrastructure

      - name: Get version
        id: tag
        run: |
          packageVersion=$(cat ClashOfHeroes/package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          echo "::set-output name=new_tag::$packageVersion"

      - name: Update ClashOfHeroes release in flux repo
        run: |
          cd infrastructure/
          sed -i -e 's/version:.*/version: "${{ steps.tag.outputs.new_tag }}"/g' prd/apps-infra/deployments/clash-of-heroes/release.yaml
          sed -i -e 's/clash-of-heroes-prd/clash-of-heroes-stg/g' prd/apps-infra/deployments/clash-of-heroes/release.yaml
          git config --global user.email "workflow@elysiumstudios.se"
          git config --global user.name "ClashOfHeroes Workflow"
          git add prd/apps-infra/deployments/clash-of-heroes/release.yaml
          git commit -m "Deploy ClashOfHeroes ${{ steps.tag.outputs.new_tag }}"
          git push

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Invalidate Cloudfront cache
        run: | 
          aws cloudfront create-invalidation --distribution-id ${{ env.CDN_DISTRIBUTION_ID }} --paths "/clash-of-heroes/*"